data_prep:
  dataset_name: "Iris Species Classification"
  feature_columns: 
    - "SepalLengthCm"
    - "SepalWidthCm"
    - "PetalLengthCm"  
    - "PetalWidthCm"
  target_column: "Species"
  
feature_prep:
  scaling_method: "StandardScaler"

model_evaluation:
  primary_metric: "macro_auc"
  cv_folds: 5
  cv_method: "StratifiedKFold"
  test_size: 0.2
  random_state: 42

model:
  model_type: "RandomForest"
  model_params:
    n_estimators: 200
    max_depth: 3
    min_samples_split: 2
    random_state: 42