data_prep:
  dataset_name: "Iris Species Classification"
  feature_columns: 
    - "SepalLengthCm"
    - "SepalWidthCm"
    - "PetalLengthCm"  
    - "PetalWidthCm"
  target_column: "Species"
  
feature_prep:
  scaling_method: "StandardScaler"
  create_ratio_features: true
  ratio_features:
    - name: "PetalSepal_Length_Ratio"
      numerator: "PetalLengthCm"
      denominator: "SepalLengthCm"
    - name: "PetalSepal_Width_Ratio"
      numerator: "PetalWidthCm"
      denominator: "SepalWidthCm"
    - name: "PetalLengthWidth_Ratio"
      numerator: "PetalLengthCm"
      denominator: "PetalWidthCm"
    - name: "SepalLengthWidth_Ratio"
      numerator: "SepalLengthCm"
      denominator: "SepalWidthCm"

model_evaluation:
  primary_metric: "macro_auc"
  cv_folds: 5
  cv_method: "StratifiedKFold"
  test_size: 0.2
  random_state: 42

model:
  model_type: "ExtraTreesClassifier"
  model_params:
    n_estimators: 100
    random_state: 42